// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_magilife : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Loc
        {
            get
            {
                return SteamVR_Actions.magilife_Loc;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TouchPadLoc
        {
            get
            {
                return SteamVR_Actions.magilife_TouchPadLoc;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrigPull
        {
            get
            {
                return SteamVR_Actions.magilife_TrigPull;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TrigGrabValue
        {
            get
            {
                return SteamVR_Actions.magilife_TrigGrabValue;
            }
        }
        
        public virtual SteamVR_Action_Vibration hapticOut
        {
            get
            {
                return SteamVR_Actions.magilife_hapticOut;
            }
        }
    }
}
